collections:
  projects:
    output: true
  authors:
    output: true
plugins:
  - jekyll-postcss
postcss:
  cache: false
exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - README.md